/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nezet;

import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author daniel.l.daniel
 */
public class PinPadForm extends javax.swing.JFrame {
    
    public static final int PIN_GOMBOK_SZAMA=10;
    
    private ArrayList<JButton> alapGombSorrend;
    private JButton[] gombok;
    private String kezdJel;
    private int kiJon;
    private int amobaMeret;
    

    /**
     * Creates new form PinPadForm
     */
    public PinPadForm() {
        initComponents();
        ujra();
        
    }
    
    private void amobaGombokGenaral(int meret){
        amobaMeret=meret;
        gombokTorol(pnlAmoba);
        gombokGeneral(pnlAmoba, amobaMeret*amobaMeret);
    }
    
    private void kezdJelBeallit(){
        kezdJel= rdoX.isSelected() ? "X" : "O";
        kiJon = kezdJel=="X" ? 0:1;
    }
    
    private void ujra(){
        checkKever.setSelected(false);
        gombokTorol(pnlPinKod);
        txtKod.setText("");
        
        pinGombokGenaral();
        gombokAlap();
        gombok=gombTombKomponensekbol();
        alapGombSorrend=gombokListbe();
        gombokraEsemeny();
    }
    
    private void gombokGeneral(JPanel pnl, int meret){
        JButton[] btns = new JButton[meret];
        for (JButton btn : btns) {
            btn = new JButton("");
            pnl.add(btn);
        }
    }
    
    private void pinGombokGenaral(){
        gombokGeneral(pnlPinKod, PIN_GOMBOK_SZAMA);
    }
    
    private void gombokraEsemeny(){
        for (JButton gomb : gombok) {
            gomb.addActionListener(new PinGombListener());
        }
    }
    
    class PinGombListener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            JButton btn = (JButton)e.getSource();
            
            btn.setBackground(Color.CYAN);
            
            String s=txtKod.getText();
            s+=btn.getText();
            
            txtKod.setText(s);
        }
        
    }
    
    private void gombokAlap() {
        JButton[] btns=gombTombKomponensekbol();
        
        for (int i = 0; i <= 8; i++) {
            btns[i].setText(i+1+"");
        }
        
        btns[btns.length-1].setText(0+"");
    }
    
    private JButton[] gombTombKomponensekbol(){
        Component[] comps = pnlPinKod.getComponents();
        JButton[] jbs=new JButton[PIN_GOMBOK_SZAMA];
        
        int ind=0;
        
        for (Component comp : comps) {
            if (comp instanceof JButton) {
                jbs[ind]=(JButton)comp;
                ind++;
            }
        }
        return jbs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mnuGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        pnlPinKod = new javax.swing.JPanel();
        pnlPinBeallit = new javax.swing.JPanel();
        checkKever = new javax.swing.JCheckBox();
        lblKod = new javax.swing.JLabel();
        txtKod = new javax.swing.JTextField();
        pnlJatek = new javax.swing.JPanel();
        pnlAmoba = new javax.swing.JPanel();
        pnlAmobaBeallit = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jatekMeretList = new javax.swing.JList<>();
        rdoX = new javax.swing.JRadioButton();
        rdoO = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuUjra = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuKilepes = new javax.swing.JMenuItem();
        mnuVizszint = new javax.swing.JMenu();
        rdoVizszint = new javax.swing.JRadioButtonMenuItem();
        rdoFuggoleges = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PinPad");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        pnlPinKod.setBorder(javax.swing.BorderFactory.createTitledBorder("Pin kód"));
        pnlPinKod.setLayout(new java.awt.GridLayout(4, 3, 5, 5));

        pnlPinBeallit.setBorder(javax.swing.BorderFactory.createTitledBorder("Beállítás"));

        checkKever.setText("kever");
        checkKever.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkKeverItemStateChanged(evt);
            }
        });

        lblKod.setText("Kód:");

        javax.swing.GroupLayout pnlPinBeallitLayout = new javax.swing.GroupLayout(pnlPinBeallit);
        pnlPinBeallit.setLayout(pnlPinBeallitLayout);
        pnlPinBeallitLayout.setHorizontalGroup(
            pnlPinBeallitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPinBeallitLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlPinBeallitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkKever)
                    .addComponent(lblKod))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlPinBeallitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtKod, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPinBeallitLayout.setVerticalGroup(
            pnlPinBeallitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPinBeallitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkKever)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPinKod, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(pnlPinBeallit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPinBeallit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPinKod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bejelentkezés", jPanel2);

        pnlAmoba.setBorder(javax.swing.BorderFactory.createTitledBorder("Amőba"));
        pnlAmoba.setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        pnlAmobaBeallit.setBorder(javax.swing.BorderFactory.createTitledBorder("Beállítás"));
        pnlAmobaBeallit.setToolTipText("");
        pnlAmobaBeallit.setLayout(new javax.swing.BoxLayout(pnlAmobaBeallit, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(30, 70));

        jatekMeretList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "3*3", "4*4", "5*5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jatekMeretList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jatekMeretList.setPreferredSize(new java.awt.Dimension(80, 30));
        jScrollPane1.setViewportView(jatekMeretList);

        pnlAmobaBeallit.add(jScrollPane1);

        buttonGroup1.add(rdoX);
        rdoX.setSelected(true);
        rdoX.setText("\"X\" kezd");
        rdoX.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jelBeallit(evt);
            }
        });
        pnlAmobaBeallit.add(rdoX);

        buttonGroup1.add(rdoO);
        rdoO.setText("\"O\" kezd");
        pnlAmobaBeallit.add(rdoO);

        javax.swing.GroupLayout pnlJatekLayout = new javax.swing.GroupLayout(pnlJatek);
        pnlJatek.setLayout(pnlJatekLayout);
        pnlJatekLayout.setHorizontalGroup(
            pnlJatekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJatekLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnlAmoba, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(pnlAmobaBeallit, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlJatekLayout.setVerticalGroup(
            pnlJatekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJatekLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlJatekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAmoba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAmobaBeallit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Játék", pnlJatek);

        jMenu1.setText("Program");

        mnuUjra.setText("Újra");
        mnuUjra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUjraActionPerformed(evt);
            }
        });
        jMenu1.add(mnuUjra);
        jMenu1.add(jSeparator1);

        mnuKilepes.setText("Kilépés");
        mnuKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKilepesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuKilepes);

        jMenuBar1.add(jMenu1);

        mnuVizszint.setText("Játék elrendezése");

        mnuGroup.add(rdoVizszint);
        rdoVizszint.setSelected(true);
        rdoVizszint.setText("vízszintes");
        rdoVizszint.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                elrendVizszintVagyFuggoleges(evt);
            }
        });
        mnuVizszint.add(rdoVizszint);

        mnuGroup.add(rdoFuggoleges);
        rdoFuggoleges.setText("függőleges");
        mnuVizszint.add(rdoFuggoleges);

        jMenuBar1.add(mnuVizszint);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkKeverItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkKeverItemStateChanged
        if (checkKever.isSelected()) {
            ArrayList<JButton> keverendoGombok = gombokListbe();
            Collections.shuffle(keverendoGombok);
            gombokTorol(pnlPinKod);
            pinPadFrissit(keverendoGombok);
            revalidate();
        }else{
            gombokTorol(pnlPinKod);
            pinPadFrissit(alapGombSorrend);
            revalidate();
        }
    }//GEN-LAST:event_checkKeverItemStateChanged

    private void mnuKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKilepesActionPerformed
        kilepes();
    }//GEN-LAST:event_mnuKilepesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        kilepes();
    }//GEN-LAST:event_formWindowClosing

    private void mnuUjraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUjraActionPerformed
        ujra();
    }//GEN-LAST:event_mnuUjraActionPerformed

    private void jelBeallit(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jelBeallit
        kezdJelBeallit();
    }//GEN-LAST:event_jelBeallit

    class ListaValasztasListener implements ListSelectionListener{

        @Override
        public void valueChanged(ListSelectionEvent e) {
            int valasztott=jatekMeretList.getSelectedIndex();
            ListModel<String> meretLista=jatekMeretList.getModel();

            char szam=meretLista.getElementAt(valasztott).charAt(0);
            amobaMeret=Integer.parseInt(Character.toString(szam));

            pnlAmoba.removeAll();
            amobaGombokGenaral(amobaMeret);
            revalidate();
            amobaGombokEsemeny();
            
            pnlAmoba.setLayout(new GridLayout(amobaMeret, amobaMeret, 5, 5));
            revalidate();
        }
        
    }
    
    private void elrendVizszintVagyFuggoleges(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_elrendVizszintVagyFuggoleges
        // TODO add your handling code here:
    }//GEN-LAST:event_elrendVizszintVagyFuggoleges

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        rdoVizszint.addItemListener(new ElrendListener());
        kezdJelBeallit();
        amobaGombokGenaral(3);
        amobaGombokEsemeny();
        jatekMeretList.addListSelectionListener(new ListaValasztasListener());
        revalidate();
    }//GEN-LAST:event_jTabbedPane1FocusGained
    
    class ElrendListener implements ItemListener{

        @Override
        public void itemStateChanged(ItemEvent e) {
            elrendVizszintVagyFuggoleges();
        }
        
    }
    
    private void elrendVizszintVagyFuggoleges(){
        int hely;
        LayoutManager lmPnl;
        if (rdoVizszint.isSelected()) {
            hely=BoxLayout.Y_AXIS;
            lmPnl = new FlowLayout();
            
        }else{
            lmPnl=new BoxLayout(pnlJatek, BoxLayout.Y_AXIS);
            hely=BoxLayout.X_AXIS;
        }
        LayoutManager lm = new BoxLayout(pnlAmobaBeallit, hely);
        pnlAmobaBeallit.setLayout(lm);
        pnlJatek.setLayout(lmPnl);
        
        revalidate();
    }
    
    private void amobaGombokEsemeny(){
        JButton[] btns = new JButton[amobaMeret*amobaMeret];
        Component[] comps=pnlAmoba.getComponents();
        
        int ind=0;
        for (Component comp : comps) {
            if (comp instanceof Component) {
                btns[ind]=(JButton) comp;
                ind++;
            }
        }
        
        for (JButton btn : btns) {
            btn.addActionListener(new AmobaGombListener());
        }
    }
    
    class AmobaGombListener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            JButton btn = (JButton)e.getSource();
            
            String jel= kiJon==0 ? "X":"O";
            btn.setText(jel);
            kiJon=1-kiJon;
        }
        
    }
    
    private void gombokTorol(JPanel pnl){
        pnl.removeAll();
    }
    
    private void kilepes(){
        int valasz=JOptionPane.showConfirmDialog(rootPane, "Kilépsz?", "Kilépés", JOptionPane.YES_NO_OPTION);
        
        if (valasz==JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }
    
    private ArrayList<JButton> gombokListbe(){
        JButton[] btns=gombTombKomponensekbol();
        ArrayList<JButton> gombok = new ArrayList<JButton>();
        for (int i = 0; i < btns.length; i++) {
            gombok.add(btns[i]);
        }
        return gombok;
    }
    
    private void pinPadFrissit(ArrayList<JButton> al){
        gombokTorol(pnlPinKod);
        for (int i = 0; i < al.size(); i++) {
            pnlPinKod.add(al.get(i));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PinPadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PinPadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PinPadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PinPadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkKever;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> jatekMeretList;
    private javax.swing.JLabel lblKod;
    private javax.swing.ButtonGroup mnuGroup;
    private javax.swing.JMenuItem mnuKilepes;
    private javax.swing.JMenuItem mnuUjra;
    private javax.swing.JMenu mnuVizszint;
    private javax.swing.JPanel pnlAmoba;
    private javax.swing.JPanel pnlAmobaBeallit;
    private javax.swing.JPanel pnlJatek;
    private javax.swing.JPanel pnlPinBeallit;
    private javax.swing.JPanel pnlPinKod;
    private javax.swing.JRadioButtonMenuItem rdoFuggoleges;
    private javax.swing.JRadioButton rdoO;
    private javax.swing.JRadioButtonMenuItem rdoVizszint;
    private javax.swing.JRadioButton rdoX;
    private javax.swing.JTextField txtKod;
    // End of variables declaration//GEN-END:variables
    

}
